# version: "3.8"

# services:
#   ollama:
#     image: ollama/ollama  # Official Ollama Docker image
#     container_name: ollama_server
#     ports:
#       - "11434:11434"
#     restart: always


#   flask_app:
#     build: .
#     container_name: flask_microservice
#     ports:
#       - "4000:4000"
#     depends_on:
#       - ollama  # Ensure Ollama starts first
#     environment:
#       - OLLAMA_HOST=http://ollama:11434
#     restart: always
